[project]
name = "cavepediav2-mcp"
version = "0.1.0"
description = "MCP for cavepediav2"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "cohere>=5.20.0",
    "dotenv>=0.9.9",
    "fastmcp>=2.13.3",
    "psycopg[binary]>=3.3.2",
]
